### healthcheck

GET http://localhost:8080/api/health HTTP/1.1

### get_usuarios

GET http://localhost:8080/api/usuarios HTTP/1.1

### get_usuario_by_id

GET http://localhost:8080/api/usuarios/3054 HTTP/1.1

### get_notificaciones

GET http://localhost:8080/api/notificaciones HTTP/1.1

### get_notificacion_by_id

GET http://localhost:8080/api/notificaciones/503 HTTP/1.1

### get_notificaciones_usuario

GET http://localhost:8080/api/usuarios/3503/notificaciones HTTP/1.1

### get_notificaciones_usuario_leidas

GET http://localhost:8080/api/usuarios/3503/notificaciones/leidas HTTP/1.1

### get_notificaciones_usuario_sin_leer

GET http://localhost:8080/api/usuarios/3503/notificaciones/sinleer HTTP/1.1
